ALTER TABLE groups
ADD COLUMN IF NOT EXISTS custom_limit_usd DECIMAL(20, 8) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS custom_window_hours INT DEFAULT NULL;

ALTER TABLE user_subscriptions
ADD COLUMN IF NOT EXISTS custom_window_start TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS custom_usage_usd DECIMAL(20, 10) NOT NULL DEFAULT 0;
